### ISSUE TITLE
Various issues setting up

### ISSUE THREAD

**Issue by christopher-beckham** [Epistimio/kleio#2]
Hi,

Thanks for writing such a cool lib!

I have various issues I would like to report (I've been using the `prototype` branch). This is currently on macOS and Python 3.6, though I'm only testing this out on Mac for the sake of learning it, and once I'm comfortable enough with Kleio I will of course be doing this all on Mila/CC.

## socket.gaierror: [Errno 8] nodename nor servname provided, or not known

With this in my `.bashrc`:

```
export KLEIO_DB_ADDRESS=mongodb://user:pass@localhost
export KLEIO_DB_NAME=orion_test
export KLEIO_DB_TYPE=MongoDB
```

I get the following error:

```
Traceback (most recent call last):
  File "/Users/cjb60/anaconda2/envs/py36/bin/kleio", line 7, in <module>
    from kleio.core.cli import main
  File "/Users/cjb60/anaconda2/envs/py36/lib/python3.6/site-packages/kleio/core/cli/__init__.py", line 14, in <module>
    from kleio.core.cli.base import KleioArgsParser
  File "/Users/cjb60/anaconda2/envs/py36/lib/python3.6/site-packages/kleio/core/cli/base.py", line 17, in <module>
    from kleio.core.cli.default import add_default_subparser
  File "/Users/cjb60/anaconda2/envs/py36/lib/python3.6/site-packages/kleio/core/cli/default.py", line 7, in <module>
    from kleio.core.io import resolve_config
  File "/Users/cjb60/anaconda2/envs/py36/lib/python3.6/site-packages/kleio/core/io/resolve_config.py", line 77, in <module>
    host=('KLEIO_DB_ADDRESS', socket.gethostbyname(socket.gethostname()))
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

I managed to work around it by hacking the `resolve_config.py` file and replacing `socket.gethostbyname(socket.gethostname())` with `os.environ['KLEIO_DB_ADDRESS']`, for the time being.

## lscpu doesn't exist on mac

I don't even think you can get this on Mac, so I just aliased it so that it doesn't throw an error when subprocess doesn't find it.

## Error trying to run experiment

Suppose I create some experiment and then try to run it, I get an error like so:

```
(py36) chris:kleio_test cjb60$ kleio run 8f6771c
Traceback (most recent call last):
  File "/Users/cjb60/anaconda2/envs/py36/bin/kleio", line 11, in <module>
    sys.exit(main())
  File "/Users/cjb60/anaconda2/envs/py36/lib/python3.6/site-packages/kleio/core/cli/__init__.py", line 39, in main
    kleio_parser.execute(argv)
  File "/Users/cjb60/anaconda2/envs/py36/lib/python3.6/site-packages/kleio/core/cli/base.py", line 136, in execute
    function(args)
  File "/Users/cjb60/anaconda2/envs/py36/lib/python3.6/site-packages/kleio/core/cli/default.py", line 260, in default
    unique_worker(consumer, args)
  File "/Users/cjb60/anaconda2/envs/py36/lib/python3.6/site-packages/kleio/core/cli/default.py", line 225, in unique_worker
    trial = TrialBuilder().build_from(args)
  File "/Users/cjb60/anaconda2/envs/py36/lib/python3.6/site-packages/kleio/core/io/trial_builder.py", line 317, in build_from
    return self.build_from_config(full_config)
  File "/Users/cjb60/anaconda2/envs/py36/lib/python3.6/site-packages/kleio/core/io/trial_builder.py", line 355, in build_from_config
    trial = self.build_view_from_config(config)
  File "/Users/cjb60/anaconda2/envs/py36/lib/python3.6/site-packages/kleio/core/io/trial_builder.py", line 297, in build_view_from_config
    trial = TrialNode.build(local=True, **config)
  File "/Users/cjb60/anaconda2/envs/py36/lib/python3.6/site-packages/kleio/core/evc/trial_node.py", line 20, in build
    trial = Trial.build(interval=interval, **kwargs)
  File "/Users/cjb60/anaconda2/envs/py36/lib/python3.6/site-packages/kleio/core/trial/base.py", line 187, in build
    trial = cls(**kwargs)
TypeError: __init__() missing 1 required positional argument: 'version'
```

Thanks!

**Comment by bouthilx** [comment]
Thanks! 

`socket.gaierror` is a common problem on mac it seems. I'll port the fix here when it is done in Oríon. But to be honest we only support and test for linux distributions, so it may take some time before this is fixed.

If you can find an alternative for `lscpu` on macs I'd be happy to merge it. :)

For the error, how did you create the experiment? Can you give the output of `kleio info 8f6771c`? If it doesn't work because of the same error, you can try `kleio pdb 8f6771c` and print `trial.metadata`. Worst case scenario, print `cmdargs` at line 170: https://github.com/Epistimio/kleio/blob/prototype/src/kleio/core/io/resolve_config.py#L170

**Comment by christopher-beckham** [comment]
Sure thing, `kleio info <id>` gives:

```
2019-04-01 02:42:55.445000: python /Users/cjb60/Desktop/kleio_test/run_test.py --name poo2
8f6771ce81068cb4dc14ca3c865afd4535824ce32727018f8e207bd98790edc306807ed708cd0778dd3b1949ab95a86bd2be806dcd324f32b76155f684b905a6
{'CPUs': {'': ''},
 'GPUs': {},
 'env_vars': {'CLUSTER': None, 'KLEIO_DATABASE_FILE_DIR': None},
 'platform': {'DEV_NULL': '/dev/null',
              'architecture': ['64bit', ''],
              'dist': ['', '', ''],
              'java_ver': ['', '', ['', '', ''], ['', '', '']],
              'kleio_version': '0.post572+gac713c8',
              'libc_ver': ['', ''],
              'linux_distribution': ['', '', ''],
              'mac_ver': ['10.13.4', ['', '', ''], 'x86_64'],
              'machine': 'x86_64',
              'node': 'chris',
              'platform': 'Darwin-17.5.0-x86_64-i386-64bit',
              'processor': 'i386',
              'python_branch': '',
              'python_build': ['default', 'Jun 28 2018 11:07:29'],
              'python_compiler': 'GCC 4.2.1 Compatible Clang 4.0.1 '
                                 '(tags/RELEASE_401/final)',
              'python_implementation': 'CPython',
              'python_revision': '',
              'python_version': '3.6.6',
              'python_version_tuple': ['3', '6', '6'],
              'release': '17.5.0',
              'system': 'Darwin',
              'uname': ['Darwin',
                        'chris',
                        '17.5.0',
                        'Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST '
                        '2018; root:xnu-4570.51.1~1/RELEASE_X86_64',
                        'x86_64',
                        'i386'],
              'version': 'Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 '
                         'PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64',
              'win32_ver': ['', '', '', '']},
 'user': 'cjb60'}
{'_pos_0': 'python',
 '_pos_1': '/Users/cjb60/Desktop/kleio_test/run_test.py',
 'name': 'poo2'}
'new'
{'HEAD_sha': '4ebe0d378df9dd6e98166f3440d6e81185b06f0b',
 'active_branch': 'master',
 'diff_sha': 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
 'is_dirty': False,
 'type': 'git'}
{parent_id: None, runtime_timestamp: None}
```

No problem with the Mac edge cases, if this works 'sufficiently' locally then once I'm comfortable with it I'll start using it on the cluster.

**Comment by bouthilx** [comment]
Oh! Looks like I didn't updated the doc about this. Try `kleio exec 8f6771c`.

**Comment by christopher-beckham** [comment]
I get this with `exec`:

```
(py36) chris:kleio_test cjb60$ kleio exec 8f6771c
Traceback (most recent call last):
  File "/Users/cjb60/anaconda2/envs/py36/bin/kleio", line 11, in <module>
    sys.exit(main())
  File "/Users/cjb60/anaconda2/envs/py36/lib/python3.6/site-packages/kleio/core/cli/__init__.py", line 39, in main
    kleio_parser.execute(argv)
  File "/Users/cjb60/anaconda2/envs/py36/lib/python3.6/site-packages/kleio/core/cli/base.py", line 136, in execute
    function(args)
  File "/Users/cjb60/anaconda2/envs/py36/lib/python3.6/site-packages/kleio/core/cli/exec.py", line 36, in main
    Consumer(root_working_dir, capture, debug).consume(trial)
TypeError: __init__() takes from 2 to 3 positional arguments but 4 were given
```

**Comment by bouthilx** [comment]
OK I fixed this problem. Sorry about that, it's just a prototype heh? :sweat_smile:

**Comment by christopher-beckham** [comment]
No problem, thanks. Ok so I tried re-running that experiment and got this:

```
(py36) chris:kleio_test cjb60$ kleio exec 8f6771c
Traceback (most recent call last):
  File "/Users/cjb60/anaconda2/envs/py36/bin/kleio", line 11, in <module>
    sys.exit(main())
  File "/Users/cjb60/anaconda2/envs/py36/lib/python3.6/site-packages/kleio/core/cli/__init__.py", line 39, in main
    kleio_parser.execute(argv)
  File "/Users/cjb60/anaconda2/envs/py36/lib/python3.6/site-packages/kleio/core/cli/base.py", line 136, in execute
    function(args)
  File "/Users/cjb60/anaconda2/envs/py36/lib/python3.6/site-packages/kleio/core/cli/exec.py", line 34, in main
    trial = TrialBuilder().build_from_id(args)
  File "/Users/cjb60/anaconda2/envs/py36/lib/python3.6/site-packages/kleio/core/io/trial_builder.py", line 337, in build_from_id
    return self.branch_from_config(config, trial=trial)
  File "/Users/cjb60/anaconda2/envs/py36/lib/python3.6/site-packages/kleio/core/io/trial_builder.py", line 378, in branch_from_config
    "{trial.short_id}".format(trial=trial))
RuntimeError: Current host differs from trial 8f6771c
```

I think this appears to be because I had to update kleio since the only thing that differs in `kleio list <id>` is the `kleio_version` tag. Though if I run `kleio exec --allow-any-change 8f6771c` I get:

```
Traceback (most recent call last):
  File "/Users/cjb60/anaconda2/envs/py36/bin/kleio", line 11, in <module>
    sys.exit(main())
  File "/Users/cjb60/anaconda2/envs/py36/lib/python3.6/site-packages/kleio/core/cli/__init__.py", line 39, in main
    kleio_parser.execute(argv)
  File "/Users/cjb60/anaconda2/envs/py36/lib/python3.6/site-packages/kleio/core/cli/base.py", line 136, in execute
    function(args)
  File "/Users/cjb60/anaconda2/envs/py36/lib/python3.6/site-packages/kleio/core/cli/exec.py", line 34, in main
    trial = TrialBuilder().build_from_id(args)
  File "/Users/cjb60/anaconda2/envs/py36/lib/python3.6/site-packages/kleio/core/io/trial_builder.py", line 337, in build_from_id
    return self.branch_from_config(config, trial=trial)
  File "/Users/cjb60/anaconda2/envs/py36/lib/python3.6/site-packages/kleio/core/io/trial_builder.py", line 385, in branch_from_config
    return self.branch_leaf(trial.id, **config)
  File "/Users/cjb60/anaconda2/envs/py36/lib/python3.6/site-packages/kleio/core/io/trial_builder.py", line 389, in branch_leaf
    trial = TrialNode.branch(trial.id, timestamp=timestamp, **config)
AttributeError: 'str' object has no attribute 'id'
```

**Comment by bouthilx** [comment]
My, my! What a terrible experience you are having with kleio for your first try, I'm sorry about that!

It seems I had a fix that I forgot to push a while ago :sweat_smile: I pushed it along with a few other modifications. I tried locally to save a trial with previous' kleio version, updated kleio and then `kleio exec <id>` and it worked. Please let me know if it does solve the problem for you too.

**Comment by christopher-beckham** [comment]
No problem, that did the trick, thanks!
